### ISSUE TITLE
mmobuff stack add does not add modifier

### ISSUE THREAD

**Issue by MadServlet** [Ehhthan/MMOBuffs-Wiki#3]
Version: MMOBuffs 1.1
Server: paper 1.18.1
Problem: Buffs are not stacking

sample config:
```
stamina_max_10:
  display-name: 'increase-stamina-by-10'
  max-stacks: 50000
  stack-type: normal
  stats:
    max_stamina: 10
  display: []
```

after applying the buff
```
/mmobuff permanent Servlet stamina_max_10 add 0
//gives no bonus as intended but ensures we have a stack registered
/mmobuff stack Servlet stamina_max_10 ADD 10
//expectation: its gonna add 10 modifier to the buff (which should add 100 to player's max stamina) 
//result: no change
```

Also, if I understood correctly, 
Modifier "Add" does not really add a stack of modifier but only adds more "Time" to the buff.
From Docs:
```
Adds the specified time to the remaining duration of the effect. This also keeps the value on the player and ignores the one specified in the command.
```

**Comment by Ehhthan** [comment]
Pushed version 1.1.2 to fix this. Will need to update the Modifiers section of the docs to be more abstract and not only apply to the time command.

**Comment by MadServlet** [comment]
tested 1.1.2, stack still not adding up.

test scenario:
```
Player current stamina: default 100
Buff to apply:
===========
stamina_max_10:
  display-name: 'increase-stamina-by-10'
  max-stacks: 50000
  stack-type: normal
  stats:
    max_stamina: 10
  display: []
===========

1. Cleared all buffs from player (stamina: 100)
2. Gave player with buff
     Before: 
        stamina: 100
     command: /mmobuff permanent Servlet stamina_max_10 add 0
     After: 
        stamina: 100
     Expectation: 
        stamina: 200
3. Gave added stack to buff:
     Before: 
        stamina: 100
     command: /mmobuff stack Servlet stamina_max_10 ADD 10
     After: 
        stamina: 100
     Expectation: 
        stamina: 200
```
